-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 14:50:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `photo` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pertanyaan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pertanyaan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `judul` VARCHAR(255) NOT NULL,
  `isi` TEXT(5000) NOT NULL,
  `tanggal_dibuat` DATETIME NOT NULL,
  `tanggal_diperbaharui` DATETIME NOT NULL,
  `vote_like` INT NULL,
  `vote_dislike` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`vote_like` ASC),
  INDEX `id_idx1` (`vote_dislike` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`vote_like`)
    REFERENCES `mydb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`vote_dislike`)
    REFERENCES `mydb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jawaban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jawaban` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isi` TEXT(5000) NOT NULL,
  `tanggal_dibuat` DATETIME NOT NULL,
  `tanggal_diperbaharui` DATETIME NOT NULL,
  `vote_like` INT NULL,
  `vote_dislike` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`vote_like` ASC),
  INDEX `id_idx1` (`vote_dislike` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`pertanyaan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`vote_like`)
    REFERENCES `mydb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`vote_dislike`)
    REFERENCES `mydb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`komentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`komentar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isi` TEXT(2000) NOT NULL,
  `tanggal_dibuat` DATETIME NOT NULL,
  `pemberi_komentar_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`pemberi_komentar_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`pemberi_komentar_id`)
    REFERENCES `mydb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`jawaban` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
